Fix: Catch times under 12h in the future
Eistbaren/client pull request #115
Opened 2022-07-18 11:01 UTC by mariusdkm

Fixes #90

2022-07-18 11:08 UTC, dorianim requested changes

2022-07-18 11:08 UTC, dorianim commented on src/components/QueryTimeslotTimePicker.tsx
> +    const diff = (newDate.getTime() - new Date().getTime()) / 3600000;
Das hier musst du in einem useEffect machen, der an der query hängt. Sonst funktioniert es nich, wenn man das Datum im Kalender ändert.

2022-07-18 11:14 UTC, dorianim commented
Und es sieht auch noch ein bisschen buggy aus: 
![image](https://user-images.githubusercontent.com/30153207/179499733-9370b38d-3828-4cf9-a915-74813cee4945.png)

2022-07-18 11:15 UTC, dorianim commented
Und es sollte verhindert werden, dass man auf book a table klicken kann, wenn die Zeit ungültig ist.
Das gilt auch bei den Tischen

2022-07-18 12:17 UTC, mariusdkm commented
> Und es sollte verhindert werden, dass man auf book a table klicken kann, wenn die Zeit ungültig ist.
Das gilt auch bei den Tischen

Ich fange des bis jetzt nur bei der Table selection ab, weil davor kann man ja auch auf `Start Browsing` klicken

2022-07-18 14:14 UTC, dorianim requested changes
Bitte noch einbauen, dass man nich weiterkommt, solange das datum falsch ist. Sonst ist der Check ein bisschen pointless 😅
Also das müsstest du auf der Landingpage und der TableSelectionPage machen :)

2022-07-19 14:02 UTC, dorianim requested changes
Bitte noch fixen, dass gewählte Zeit außerhalb der Öffnungszeiten nicht akzeptiert wird auf der TableSelectionPage :)

2022-07-19 14:28 UTC, dorianim requested changes
Teste das doch mal lokal, bevor dus pusht xD

2022-07-21 20:32 UTC, dorianim approved these changes
LGTM!

2022-07-21 20:34 UTC, merged