Feat/connect routes
Eistbaren/client pull request #55
Opened 2022-06-27 21:24 UTC by lamorak13

Fügt den Seiten Connectivität hinzu mit Hilfe des react-router Link Component. 

Änderungen in der URL werden automatisch registriert und ändern den activeStep in der Menüleiste

` const routes = ['/', '/search', '/table', '/personal-data'];`
`useEffect(() => {
    const index = routes.indexOf(location.pathname);
    setStep(index >= 0 ? index : 0);
  }, [location]);`

2022-06-27 21:28 UTC, lamorak13 commented
Fixes #46 
Die Reservation approval Seite bekommt checkt, ob die Reservierung innerhalb der nächsten 24h ist. In dem Fall wird der Bestätigen Button gerendert. Stornieren ist immer möglich.

2022-06-28 08:58 UTC, dorianim requested changes
Noch bei der reservation-approval die ID von der Reservtion in den Pfad hauen, dann passts

2022-06-28 11:20 UTC, dorianim requested changes

2022-06-28 11:21 UTC, dorianim approved these changes
Umbenennen in einer separaten PR für #56

2022-06-28 11:21 UTC, merged