🐻‍❄️ Feat: Clickable locations and close popups
Eistbaren/client pull request #72
Opened 2022-07-04 16:45 UTC by mariusdkm

Fixes #60

2022-07-04 16:49 UTC, dorianim requested changes
Kannst du noch so einen fade effekt machen wie bei dem Popup? Das ist mega easy.

2022-07-04 20:17 UTC, dorianim requested changes
Mach bitte noch das Icon

2022-07-05 12:05 UTC, mariusdkm commented
<img width="373" alt="Screenshot 2022-07-05 at 14 05 26" src="https://user-images.githubusercontent.com/43829743/177323474-6ab42558-aa25-4ed4-9f61-ab7dd5ad4470.png">
Sieht jetzt so aus

2022-07-05 12:14 UTC, LadnerJonas approved these changes
Farbe passt schon

2022-07-05 12:42 UTC, dorianim approved these changes
Ich finde es sehr schade, dass du keinen Fade eingebaut hast, aber nagut :(

2022-07-05 12:47 UTC, merged