🚀 Feat: details page redesign
Eistbaren/client pull request #99
Opened 2022-07-12 20:11 UTC by mariusdkm

Ich bin noch nicht zufrieden damit, jedoch fällt mir nicht ein, wie man das schöner machen könnte.
Bin für alle Vorschläge offen

Fixes #97

2022-07-12 20:17 UTC, dorianim commented
Hmm ja, schwierig... Also ich finde die Karte mit dem Restaurant sehr nice!
Probier vielleicht mal, die Daten nich auf eine Karte zu machen, sondern direkt auf den Hintergrund, so wie auf der Seite davor?

2022-07-12 21:07 UTC, dorianim requested changes
![image](https://user-images.githubusercontent.com/30153207/178595424-4be9d7e7-9925-4c21-ab78-f6a4527a1c46.png)
bei einem Fehler ists noch bisschen buggy

2022-07-13 20:31 UTC, mariusdkm commented
f***, dass mit dem rebase muss ich nochmal üben

2022-07-14 06:27 UTC, dorianim requested changes
Ich hoffe, die suggestions passen so, war ein bisschen schwierig mit dem großen Diff :sweat_smile: 

Sieht jetzt IMO sehr gut aus!

2022-07-14 06:27 UTC, dorianim commented on src/pages/ReservationDetails.tsx
> +              {reservation ? (
```suggestion
              {reservation && (
```

2022-07-14 06:27 UTC, dorianim commented on src/pages/ReservationDetails.tsx
> +              ) : null}
```suggestion
              )}
```

2022-07-14 06:27 UTC, dorianim commented on src/pages/ReservationDetails.tsx
> +            <img src='/logo-big.png' className='personal-data-image' />
Wenn du die Klasse benutzt, bitte umbenennen

2022-07-14 06:27 UTC, dorianim commented on src/pages/ReservationDetails.tsx
> +          {showReservation ? (
```suggestion
          {showReservation && (
```

2022-07-14 06:27 UTC, dorianim commented on src/pages/ReservationDetails.tsx
> +          ) : null}
```suggestion
          )}
```

2022-07-14 06:27 UTC, dorianim commented on src/pages/ReservationDetails.tsx
> +                console.log(t.restaurantId);
```suggestion
```

2022-07-14 09:41 UTC, dorianim requested changes
Bitte bei einem Fehler noch die Card ausblenden, ansonsten siehts gut aus :)

2022-07-15 07:39 UTC, dorianim requested changes
Bitte noch die Box vertikal zentrieren, so wie auf der personal data page:
![image](https://user-images.githubusercontent.com/30153207/179175824-008aece2-7cfe-4f96-80da-919fd5893a5f.png) (https://feat-details-page-redesign.reservation-bear.pages.dev/reservation-details/63c081a5-17a3-44b3-8a26-b250186288dd)
![image](https://user-images.githubusercontent.com/30153207/179175888-4202687c-a09b-44eb-9922-a21acc42f95b.png)

Und vielleicht würde es nice aussehen, wenn die Restaurant card über dem Formular wäre? Weil dann wär es ein bisschen ausgeglichener. Im Moment ist links sehr viel und rechts eher wenig.

2022-07-15 16:57 UTC, dorianim approved these changes
Wundervoll!

2022-07-15 17:13 UTC, merged